Actually fail if the tag and the chart don't match.

diff --git a/.circleci/config.yml.d/amb_util.yml b/.circleci/config.yml.d/amb_util.yml
--- a/.circleci/config.yml.d/amb_util.yml
+++ b/.circleci/config.yml.d/amb_util.yml
@@ -140,6 +140,6 @@ commands:
             thisversion=$(grep version: charts/ambassador/Chart.yaml | awk ' { print $2 }')
 
             if [[ "<< pipeline.git.tag >>" != "chart-test-v${thisversion}" ]]; then
-              echo "Chart version ${thisversion} doesn't match tag << pipeline.git.tag >>; halting"
-              circleci step halt
+              echo "Chart version ${thisversion} doesn't match tag << pipeline.git.tag >>; aborting"
+              exit 1
             fi
